- host: 45.130.9.101
  port: 2302
  username: cisco
  password: cisco
  secret: cisco
  device_type: cisco_ios
- host: 45.130.9.101
  port: 2303
  username: cisco
  password: cisco
  secret: cisco
  device_type: cisco_ios
- host: 45.130.9.101
  port: 2304
  username: cisco
  password: cisco
  secret: cisco
  device_type: cisco_ios
- host: 45.130.9.101
  port: 2305
  username: cisco
  password: cisco
  secret: cisco
  device_type: cisco_ios
- host: 45.130.9.101
  port: 2306
  username: cisco
  password: cisco
  secret: cisco
  device_type: cisco_ios
